# Generated by Django 5.2.4 on 2025-08-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_is_wishlisted_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_wishListed',
        ),
    ]
