# Generated by Django 5.2.4 on 2025-08-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_bid_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='maker',
            new_name='bidmaker',
        ),
    ]
