# Generated by Django 5.2.4 on 2025-08-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_maker_bid_bidmaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
