# Generated by Django 5.2.4 on 2025-08-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bid_date_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
    ]
